### ISSUE TITLE
2.1 的作用是什么？

### ISSUE THREAD

**Issue by LeoLiuYan** [alfredhuang211/study-docker-doc#1]
docker跨主机macvlan网络配置.md
2.1 步骤的作用是什么？

**Comment by alfredhuang211** [comment]
是指的创建vlan这个步骤么?
这个操作是在两台主机之间创建了一个vlan.然后后续的是让容器通过这个vlan进行通讯.
当然实际是可以在多个主机间来创建vlan的.只要vlan的id相同,那么就属于同一个vlan.在这个vlan上的主机或容器之间就都是通的.
