### ISSUE TITLE
不能联通宿主机的问题

### ISSUE THREAD

**Issue by recall704** [alfredhuang211/study-docker-doc#2]
按着步骤搭建后，发现两台机器的容器可以互相ｐｉｎｇ通，但是容器不能ｐｉｎｇ通宿主机的地址。也不能ｐｉｎｇ通外网。应该怎么做呢？
两台机器均是使用ＶＭ虚拟出来ｃｅｎｔｏｓ７．２，ｄｏｃｋｅｒ版本是１．１２　。

**Comment by alfredhuang211** [comment]
是哪种方式搭建的呢?是搭建的什么样的网络呢?容器都放在vxlan里面了么?如果使用了vxlan,在vxlan内的容器或主机才可互相ping通.
