### ISSUE TITLE
macvlan模式ping不同另外主机的容器

### ISSUE THREAD

**Issue by icefed** [alfredhuang211/study-docker-doc#3]
配置了macvlan模式的网络，不管使用vlan还是不使用都只能ping通本机的容器，ping不通另外主机的容器，网关也ping不通。
也开启混杂模式了，不知道是不是没有生效或者什么缘故。macvlan模式在linux主机配置vlan还需要在交换机配置吗？
谢谢。

**Comment by alfredhuang211** [comment]
使用vlan只是把两个macvlan的容器包装在一个vlan内，不是必须的。
ping通本主机容器，是从主机发起还是从另外的容器发起？从本主机ping本主机的macvlan容器，理论上应该是不通的，因为docker对这块本身做了限制。
不知道两主机相连用的什么样的交换机，有些交换机，或者虚假交换机也会限制混杂模式，需要开启交换机的混杂模式支持。

**Comment by icefed** [comment]
不好意思没表达清楚，从容器内ping同主机的另外一个容器能ping通，不同主机的容器ping不通。
对vlan网络这块不太了解，交换机也不太清楚。如果硬件环境问题可能不会采用这个方案，目前在看calico方案。
感谢答复。

**Comment by alfredhuang211** [comment]
多探讨一起学习呗。本身同主机容器互ping因为还有本身的docker0网桥，所以有可能是可以通的。在容器类具体看有几个iface，可以判定macvlan的口有没有通。如果最终目的只是要进行容器间通信，calico和flannel的方案都很好。macvlan更擅长的应该是怎么把容器暴露到现有网络中。

**Comment by cylonchau** [comment]
请问一下解决了吗、？我也是相同的问题
